ref: /mnt/d/2023/EPICS/EPIC_ITD_781_PRS/ITD_1030_PRS_Panel_quality/02_analyses/00_ref/human_g1k_v37_decoy.fasta
idatfolder: /mnt/d/2023/ITD/ITD_2154_KK_arraydata/Ramis_GSA/20220930_Rami-GSA-24_Chip07/206560790057/
clusterfile_egt: data/GSA-24v3-0_A1_ClusterFile.egt
manifest_bpm: data/GSA-24v3-0_A1.bpm